array_width = 120
binop_separator = "Back"
chain_width = 120
comment_width = 222
condense_wildcard_suffixes = true
# disable_all_formatting = true
edition = "2021"
enum_discrim_align_threshold = 5
fn_call_width = 120
fn_params_layout = "Compressed"
fn_single_line = false
force_explicit_abi = false
format_code_in_doc_comments = true
imports_granularity = "Module"
imports_layout = "Horizontal"
match_block_trailing_comma = true
max_width = 160
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 150
struct_lit_width = 40
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
